[package]
name = "CAH"
version = "0.1.0"
authors = ["anshuman"]

[dependencies]
rand = "0.3"
serde = "0.4.0"
serde_codegen = "0.4.0"
serde_macros = "0.4.0"

[dependencies.piston]
git = "https://github.com/PistonDevelopers/piston.git"

[dependencies.piston2d-graphics]
git = "https://github.com/PistonDevelopers/graphics.git"

[dependencies.pistoncore-sdl2_window]
git = "https://github.com/PistonDevelopers/sdl2_window.git"

[dependencies.piston2d-opengl_graphics]
git = "https://github.com/PistonDevelopers/opengl_graphics.git"